/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.5-dev at Sun Jan 24 22:34:30 2016. */

#include "coffee.pb.h"

#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t CoffeeCommand_fields[3] = {
    PB_FIELD(  1, UENUM   , OPTIONAL, STATIC  , FIRST, CoffeeCommand, type, type, 0),
    PB_FIELD(  2, BYTES   , OPTIONAL, CALLBACK, OTHER, CoffeeCommand, command, type, 0),
    PB_LAST_FIELD
};

const pb_field_t Response_fields[3] = {
    PB_FIELD(  1, UENUM   , OPTIONAL, STATIC  , FIRST, Response, type, type, 0),
    PB_FIELD(  2, STRING  , OPTIONAL, CALLBACK, OTHER, Response, description, type, 0),
    PB_LAST_FIELD
};


