/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.5-dev at Sun Jan 24 22:34:30 2016. */

#ifndef PB_COFFEE_PB_H_INCLUDED
#define PB_COFFEE_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Enum definitions */
typedef enum _CoffeeCommand_CommandType {
    CoffeeCommand_CommandType_OPERATION = 0,
    CoffeeCommand_CommandType_QUERY = 1
} CoffeeCommand_CommandType;

typedef enum _Response_ResponseType {
    Response_ResponseType_OK = 0,
    Response_ResponseType_ERR = 1,
    Response_ResponseType_NO_WATER = 2,
    Response_ResponseType_NO_BEAN = 3,
    Response_ResponseType_FORMAT_UNKN = 4
} Response_ResponseType;

/* Struct definitions */
typedef struct _CoffeeCommand {
    bool has_type;
    CoffeeCommand_CommandType type;
    pb_callback_t command;
} CoffeeCommand;

typedef struct _Response {
    bool has_type;
    Response_ResponseType type;
    pb_callback_t description;
} Response;

/* Default values for struct fields */

/* Initializer values for message structs */
#define CoffeeCommand_init_default               {false, (CoffeeCommand_CommandType)0, {{NULL}, NULL}}
#define Response_init_default                    {false, (Response_ResponseType)0, {{NULL}, NULL}}
#define CoffeeCommand_init_zero                  {false, (CoffeeCommand_CommandType)0, {{NULL}, NULL}}
#define Response_init_zero                       {false, (Response_ResponseType)0, {{NULL}, NULL}}

/* Field tags (for use in manual encoding/decoding) */
#define CoffeeCommand_type_tag                   1
#define CoffeeCommand_command_tag                2
#define Response_type_tag                        1
#define Response_description_tag                 2

/* Struct field encoding specification for nanopb */
extern const pb_field_t CoffeeCommand_fields[3];
extern const pb_field_t Response_fields[3];

/* Maximum encoded size of messages (where known) */

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define COFFEE_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
