# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: coffee.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='coffee.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x0c\x63offee.proto\"s\n\rCoffeeCommand\x12(\n\x04type\x18\x01 \x01(\x0e\x32\x1a.CoffeeCommand.CommandType\x12\x0f\n\x07\x63ommand\x18\x02 \x01(\x0c\"\'\n\x0b\x43ommandType\x12\r\n\tOPERATION\x10\x00\x12\t\n\x05QUERY\x10\x01\x62\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_COFFEECOMMAND_COMMANDTYPE = _descriptor.EnumDescriptor(
  name='CommandType',
  full_name='CoffeeCommand.CommandType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='OPERATION', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='QUERY', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=92,
  serialized_end=131,
)
_sym_db.RegisterEnumDescriptor(_COFFEECOMMAND_COMMANDTYPE)


_COFFEECOMMAND = _descriptor.Descriptor(
  name='CoffeeCommand',
  full_name='CoffeeCommand',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='CoffeeCommand.type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='command', full_name='CoffeeCommand.command', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _COFFEECOMMAND_COMMANDTYPE,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=16,
  serialized_end=131,
)

_COFFEECOMMAND.fields_by_name['type'].enum_type = _COFFEECOMMAND_COMMANDTYPE
_COFFEECOMMAND_COMMANDTYPE.containing_type = _COFFEECOMMAND
DESCRIPTOR.message_types_by_name['CoffeeCommand'] = _COFFEECOMMAND

CoffeeCommand = _reflection.GeneratedProtocolMessageType('CoffeeCommand', (_message.Message,), dict(
  DESCRIPTOR = _COFFEECOMMAND,
  __module__ = 'coffee_pb2'
  # @@protoc_insertion_point(class_scope:CoffeeCommand)
  ))
_sym_db.RegisterMessage(CoffeeCommand)


# @@protoc_insertion_point(module_scope)
